baseURL = "https://pascom.netlify.com/"
theme = "dot"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true


[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
primaryColor = "#d20134"
secondaryColor = "#f9f9f9"
textColor = "#666666"
textColorDark = "#000000"
whiteColor = "#ffffff"


[Languages]

  # English Language
  [Languages.en]
  languageName = "En"
  weight = 1
  languageCode = "en-us"
  title = "PASCOM"
  dateFormat = "2 January 2006"
  home = "Home"
  logo = "images/logo_white.png"
  logoAlt = "images/logo.png"
  copyright = "Copyright © 2019 a theme by themefisher.com"

    # navigation
    [Languages.en.menu]
    
      [[Languages.en.menu.main]]
        weight = 2
        name = "Faq"
        url = "en/faq"
        
      [[Languages.en.menu.main]]
        weight = 2
        name = "contact"
        url = "en/contact"
      

    # algolia
    [Languages.en.params]
    algoliaindex = "doc-productive-en"
    legalnoticeUrl = "legal-notice"

    # banner
    [Languages.en.params.banner]
      title = "Support Center & Knowledge base"
      description = "Find advice and answers from our support team fast or get in touch"
      image = "images/banner.jpg"
      placeholder = "Have a question? Just ask here or enter terms"

    # Topics
    [Languages.en.params.topics]
      title = "Find your answer by subject"
    
    # call to action
    [Languages.en.params.cta]
      enable = true
      title = "Didn't find an answer to your question?"
      description = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
      btnText = "contact us"
      btnURL = "en/contact"

    # contact
    [Languages.en.params.contact]
      title = "Got Any Questions"
      content = "Submit the form and confirm your email address at <a class='text-primary' href='https://formspree.io/'>Formspree</a> Then add the following lines to contact page YAML Front Matter."

    # footer social icon
    [[Languages.en.socialIcon]]
      icon = "fab fa-facebook-f"
      linkURL = "http://www.facebook.com/pascom.net"

    [[Languages.en.socialIcon]]
      icon = "fab fa-twitter"
      linkURL = "http://twitter.com/pascom_net"
      
    [[Languages.en.socialIcon]]
      icon = "fab fa-youtube"
      linkURL = "http://www.youtube.com/user/pascomnet"



  # German Language
  [Languages.de]
  languageName = "De"
  weight = 1
  languageCode = "de"
  title = "PASCOM"
  dateFormat = "2 January 2006"
  home = "Aidez-moi"
  logo = "images/logo_white.png"
  logoAlt = "images/logo.png"
  copyright = "Copyright © 2019 a theme by themefisher.com"

    # navigation
    [Languages.de.menu]
    
      [[Languages.de.menu.main]]
        weight = 2
        name = "Faq"
        url = "de/faq"

      [[Languages.de.menu.main]]
        weight = 2
        name = "contact"
        url = "de/contact"



    # algolia
    [Languages.de.params]
    algoliaindex = "doc-productive-de"
    legalnoticeUrl = "legal-notice"


    # banner
    [Languages.de.params.banner]
      title = "Comment pouvons nous aider?"
      description = "Trouvez rapidement des conseils et des réponses auprès de notre équipe d'assistance ou contactez-nous."
      image = "images/banner.jpg"
      placeholder = "Have a question? Just ask here or enter terms"

    # pages
    [Languages.de.params.pages]
      title = "Parcourir tous les sujets"
    
    # call to action
    [Languages.de.params.cta]
      enable = true
      title = "Vous n'avez pas trouvé de réponse à votre question?"
      description = "Contactez-nous pour plus de détails sur les services supplémentaires et la tarification du travail personnalisé"
      btnText = "Contactez nous"
      btnURL = "de/contact/"

    # contact
    [Languages.de.params.contact]
      title = "Vous avez des questions"
      content = "Envoyez le formulaire et confirmez votre adresse e-mail à l'adresse <a class='text-primary' href='https://formspree.io/'>Formspree</a> Ajoutez ensuite les lignes suivantes pour contacter la page YAML Front Matter."

    # footer social icon
    [[Languages.de.socialIcon]]
      icon = "fab fa-facebook-f"
      linkURL = "http://www.facebook.com/pascom.net"

    [[Languages.de.socialIcon]]
      icon = "fab fa-twitter"
      linkURL = "http://twitter.com/pascom_net"
      
    [[Languages.de.socialIcon]]
      icon = "fab fa-youtube"
      linkURL = "http://www.youtube.com/user/pascomnet"